stages:
    - build
    - deploy

# build stage
build_app:
    image: node:alpine
    stage: build
    only:
        - master
    script:
       - npm install
       - npm run build
    cache:
      paths:
        - node_modules/ 
    artifacts:
        paths:
            # build folder
            - dist/
        expire_in: 1 hour

# production stage
production:
    stage: deploy
    before_script:
        - apt-get update -qy
        - apt-get install -y lftp
    script:
        # Sync to FTP
        - lftp -e "open ftp://api.sde.ru.com; user u1041581 pE!OYj9g; mirror -X .* -X .*/ --reverse --verbose --delete dist/ form/; bye"
