language: node_js
node_js:
  - node
cache: npm
script:
  - npm run build

deploy:
  provider: pages
  cleanup: false
  github_token: '$GITHUB_TOKEN'
  local_dir: dist
  on:
    branch: master

after-script:
  - npm run deploy

env:
  - ftpHost=$ftpHost
  - ftpPort=$ftpPort
  - ftpUsr=$ftpUsr
  - ftpPwd=$ftpPwd
