language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

after_success: 'curl -T dist -u $SFTP_USER:$SFTP_PASSWORD ftp://api.sde.ru.com/form/'
