language: node_js
node_js:
  - 10.16.0
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:

script:
  - npm run build

after_script:
  - npm run deploy

branches:
  only:
    - master

env:
  - ftpHost=$ftpHost
  - ftpPort=$ftpPort
  - ftpUsr=$ftpUsr
  - ftpPwd=$ftpPwd
